Repository pylhc/tfs, pull requests merged in 2023-04, with the labels that each got.

#119 Pandas 2.x restraint
  .github/workflows/cron.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  setup.py
  tfs/__init__.py
  tfs/frame.py
Labels: Bug, CI/CD

#120 Release 3.6.0 and removal of TfsDataFrame methods
  CHANGELOG.md
  setup.py
  tests/test_frame.py
  tests/test_writer.py
  tfs/__init__.py
  tfs/frame.py
Labels: Minor, CI/CD

#122 TFSCollections cleaned and with paths
  CHANGELOG.md
  tests/test_collection.py
  tests/test_frame.py
  tests/test_reader.py
  tfs/__init__.py
  tfs/collection.py
Labels: Enhancement, Minor
